/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-crash.h
 #	source generated by 4D Plugin Wizard
 #	Project : crash
 #	author : miyako
 #	2025/03/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CRASH_H
#define PLUGIN_CRASH_H

#include "4DPluginAPI.h"

#pragma mark -

static void CRASH_4D(PA_PluginParameters params);

#endif /* PLUGIN_CRASH_H */
